// templates.ts
// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { Element, Page } from "@/app/lib/store"; // Adjust path to your store

export const templates: Record<string, Page[]> = {
  "landing-page": [
    {
      id: "landing-home",
      title: "Home",
      elements: [
        {
          id: Date.now(),
          type: "header",
          x: 0,
          y: 0,
          width: 1200,
          height: 80,
          content: "My Awesome Landing Page",
          style: {
            backgroundColor: "#1f2937",
            color: "#ffffff",
            fontSize: "24px",
            textAlign: "center",
            lineHeight: "80px",
          },
        },
        {
          id: Date.now() + 1,
          type: "text",
          x: 50,
          y: 120,
          width: 1100,
          height: 100,
          content: "Welcome to my site!\nClick below to learn more.",
          style: { fontSize: "18px", textAlign: "center" },
        },
        {
          id: Date.now() + 2,
          type: "button",
          x: 500,
          y: 240,
          width: 200,
          height: 50,
          content: "Get Started",
          style: {
            backgroundColor: "#3b82f6",
            color: "#ffffff",
            fontSize: "16px",
            borderRadius: "8px",
            textAlign: "center",
            lineHeight: "50px",
          },
        },
        {
          id: Date.now() + 3,
          type: "image",
          x: 350,
          y: 320,
          width: 500,
          height: 300,
          content: "https://via.placeholder.com/500x300",
          style: { borderRadius: "10px" },
        },
        {
          id: Date.now() + 4,
          type: "icon",
          x: 580,
          y: 640,
          width: 40,
          height: 40,
          content: "FaStar",
          style: { color: "#f59e0b", fontSize: "24px" },
        },
      ],
      backgroundColor: "#f9fafb",
      frameHeight: 800,
    },
    {
      id: "landing-about",
      title: "About",
      elements: [
        {
          id: Date.now() + 5,
          type: "text",
          x: 50,
          y: 50,
          width: 1100,
          height: 150,
          content: "About Us\nWe’re a team passionate about building great things.",
          style: { fontSize: "20px", textAlign: "center" },
        },
        {
          id: Date.now() + 6,
          type: "image",
          x: 450,
          y: 220,
          width: 300,
          height: 200,
          content: "https://via.placeholder.com/300x200",
          style: { borderRadius: "5px" },
        },
        {
          id: Date.now() + 7,
          type: "button",
          x: 525,
          y: 450,
          width: 150,
          height: 40,
          content: "Contact Us",
          style: {
            backgroundColor: "#10b981",
            color: "#ffffff",
            fontSize: "14px",
            borderRadius: "6px",
            textAlign: "center",
            lineHeight: "40px",
          },
        },
      ],
      backgroundColor: "#ffffff",
      frameHeight: 600,
    },
  ],
  "portfolio": [
    {
      id: "portfolio-home",
      title: "Portfolio Home",
      elements: [
        {
          id: Date.now() + 8,
          type: "nav",
          x: 0,
          y: 0,
          width: 1200,
          height: 60,
          content: "Home,Projects,Contact",
          style: {
            backgroundColor: "#111827",
            color: "#ffffff",
            fontSize: "16px",
            textAlign: "center",
          },
        },
        {
          id: Date.now() + 9,
          type: "text",
          x: 50,
          y: 100,
          width: 1100,
          height: 80,
          content: "My Work\nA showcase of my projects.",
          style: { fontSize: "22px", textAlign: "center" },
        },
        {
          id: Date.now() + 10,
          type: "image",
          x: 50,
          y: 200,
          width: 350,
          height: 250,
          content: "https://via.placeholder.com/350x250",
          style: { borderRadius: "8px" },
        },
        {
          id: Date.now() + 11,
          type: "image",
          x: 425,
          y: 200,
          width: 350,
          height: 250,
          content: "https://via.placeholder.com/350x250",
          style: { borderRadius: "8px" },
        },
        {
          id: Date.now() + 12,
          type: "image",
          x: 800,
          y: 200,
          width: 350,
          height: 250,
          content: "https://via.placeholder.com/350x250",
          style: { borderRadius: "8px" },
        },
        {
          id: Date.now() + 13,
          type: "button",
          x: 500,
          y: 480,
          width: 200,
          height: 50,
          content: "View More",
          style: {
            backgroundColor: "#8b5cf6",
            color: "#ffffff",
            fontSize: "16px",
            borderRadius: "8px",
            textAlign: "center",
            lineHeight: "50px",
          },
        },
      ],
      backgroundColor: "#f3f4f6",
      frameHeight: 600,
    },
  ],
};